import React from 'react';
import ReactDOM from 'react-dom';

function TodoEntry(todoListEntry, index, onClicked) {
    return (
        <li key={index}>
            <input type="checkbox"
                checked={todoListEntry.isDone}
                onChange={onClicked}/>
            {todoListEntry.text}
        </li>
    )
}

class Todo extends React.Component {
    constructor() {
        super();
        this.state = {
            todoList: [] // Start with an empty todo list.
            };
    }

    todoEntryClicked(index)
    {
        const newIsDone = !this.state.todoList[index].isDone;
        const xmlhttp = new XMLHttpRequest();

        xmlhttp.onreadystatechange = () => {
            if (xmlhttp.readyState == XMLHttpRequest.DONE &&
                xmlhttp.status == 200)
            {
                const todoEntryForIndex = JSON.parse(xmlhttp.responseText);
                const todoList = this.state.todoList.slice();
                todoList[index] = todoEntryForIndex;
                this.setState({
                    todoList
                });
            }
        }

        xmlhttp.open("POST", `api/todo/${index}`, true);
        xmlhttp.send(JSON.stringify({isDone: newIsDone}));
    }

    componentDidMount() {
        const xmlhttp = new XMLHttpRequest();

        xmlhttp.onreadystatechange = () => {
            if (xmlhttp.readyState == XMLHttpRequest.DONE &&
                xmlhttp.status == 200) {
                const todoList = JSON.parse(xmlhttp.responseText);
                this.setState({
                    todoList
                })
            }
        }

        xmlhttp.open("GET", "api/todo", true);
        xmlhttp.send();
    }

    render() {
        return (
            <div>This is generated by React...
            <ul>
                { this.state.todoList.map(
                    (todoListEntry, index) => {
                        return TodoEntry(todoListEntry, index,
                            () => { this.todoEntryClicked(index); });
                    }
                ) }
            </ul>
            </div>
        );
    }
}

// ========================================

ReactDOM.render(
  <Todo/>,
  document.getElementById('todoRoot')
);
