import React from 'react';
import ReactDOM from 'react-dom';

function TodoEntry(todoListEntry, index, onClicked) {
    return (
        <li key={index}>
            <input type="checkbox"
                checked={todoListEntry.isDone}
                onChange={onClicked}/>
            {todoListEntry.text}
        </li>
    )
}

class Todo extends React.Component {
    constructor() {
        super();
        this.state = {
            todoList: [
                { isDone: true,  text: "Something old" },
                { isDone: true,  text: "Something new" },
                { isDone: true,  text: "Something borrowed" },
                { isDone: true,  text: "Something blue" } ]
            };
    }

    todoEntryClicked(index)
    {
        const todoList = this.state.todoList.slice();
        todoList[index].isDone = !todoList[index].isDone;
        this.setState({
            todoList
        });
    }

    render() {
        return (
            <div>This is generated by React...
            <ul>
                { this.state.todoList.map(
                    (todoListEntry, index) => {
                        return TodoEntry(todoListEntry, index,
                            () => { this.todoEntryClicked(index); });
                    }
                ) }
            </ul>
            </div>
        );
    }
}

// ========================================

ReactDOM.render(
  <Todo/>,
  document.getElementById('todoRoot')
);
