import React from 'react';
import ReactDOM from 'react-dom';

function TodoEntry(props, index) {
    return (
        <li key={index}>
            <input type="checkbox" defaultChecked={props.isDone} /> {props.text}
        </li>
    )
}

class Todo extends React.Component {
    constructor() {
        super();
        this.state = {
            todoList: [ { isDone: true,  text: "Default" } ]
            };
    }

    render() {
        return (
            <div>This is generated by React...
            <ul>
                { this.state.todoList.map(TodoEntry) }
            </ul>
            </div>
        );
    }
}

// ========================================

ReactDOM.render(
  <Todo/>,
  document.getElementById('todoRoot')
);
